name: Send mail on PR
on:
  pull_request_target:
    types: [opened]
jobs:
  send_mail:
    runs-on: ubuntu-latest
    steps:
      - uses: kceb/pull-request-url-action@v1
        id: pr-url
      - name: Create mail body 📝
        run: |
          MY_STRING=$(cat << EOF
          New Pull Request to Review on ${{ github.repository }}

          ${{ steps.pr-url.outputs.url }}

          EOF
          )
          MY_STRING="${MY_STRING//'%'/'%25'}"
          MY_STRING="${MY_STRING//$'\n'/'%0A'}"
          MY_STRING="${MY_STRING//$'\r'/'%0D'}"
          echo "::set-output name=content::$MY_STRING"
        id: mail_body
      - name: Send mail 📧
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_HOST }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{ github.event.pull_request.title }}
          to: ${{ secrets.MAIL_TO_ADDRESS }}
          from: netcup Community
          secure: false
          body: ${{ steps.mail_body.outputs.content }}
          ignore_cert: true
